### ISSUE TITLE
glide install error message but go build successfully

### ISSUE THREAD

**Issue by txgo** [wercker/wercker#10]
[ERROR] Dependency /home/txgo/work/src/github.com/wercker/wercker/vendor/github.com/docker/docker/api/client/formatter failed to resolve: lstat /home/txgo/work/src/github.com/wercker/wercker/vendor/github.com/docker/docker/api/client/formatter: no such file or directory.
[ERROR] Failed to retrieve a list of dependencies: lstat /home/txgo/work/src/github.com/wercker/wercker/vendor/github.com/docker/docker/api/client/formatter: no such file or directory

**Comment by faiq** [comment]
Thanks for the interest in the project. Just to be clear, you were able to run `go build` and get a properly functioning binary, right? We can look into what's causing these glide errors! Thanks for reporting

**Comment by termie** [comment]
glide unfortunately prints all kinds of errors and warnings when doing an install, it's known but doesn't seem to have an affect on the actual build
