### ISSUE TITLE
Building on Wercker Debian stopped working

### ISSUE THREAD

**Issue by Skarlso** [wercker/wercker#101]
Hi. A couple of days ago it seems wercker stopped working on a Debian distro. 

This is the error I'm getting:

```
The following packages have unmet dependencies:
git : Depends: liberror-perl but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

This is the configuration file, I'm using: 

    box: debian
    build:
        steps:
            - arjen/hugo-build:
                theme: redlounge
    deploy:
        steps:
            - install-packages:
                packages: git ssh-client
            - leipert/git-push:
                gh_oauth: $GIT_TOKEN
                repo: skarlso/skarlso.github.io
                branch: master
                basedir: public    

This was working fine without any problems.

**EDIT**: Changing the distro to 'ubuntu' fixes this issue.
**EDIT2**: No, it did not fix it:

```
E: Unable to locate package git
E: Unable to locate package ssh-client
```

**Comment by Tonnu** [comment]
Hi there, you've hopefully resolved this issue by now, but for future reference: these kind of errors can be usually solved by clearing the cache (that means hitting the `clear cache` button on the Wercker platform or removing the `./wercker/cache` directory locally).
