### ISSUE TITLE
replace calls to CopyFromContainer with DownloadFromContainer

### ISSUE THREAD

**Issue by mwhooker** [wercker/wercker#107]
If we use the new api, we can check if the size is bigger than allowed before we do any work

https://github.com/fsouza/go-dockerclient/blob/master/container.go#L998
https://docs.docker.com/engine/reference/api/docker_remote_api_v1.20/#get-an-archive-of-a-filesystem-resource-in-a-container

**Comment by hatchan** [comment]
Resolved in #196
