### ISSUE TITLE
Builds fail without an error when artifacts > 1GB

### ISSUE THREAD

**Issue by flenter** [wercker/wercker#110]
We should provide feedback in the log/output on why the build is failing.

Ideally this is done in the logs as well as via the `message` (that's the error/success text displayed on the build overview page)

**Comment by mwhooker** [comment]
a good resolution for this would be to 

- [ ] make sure sure `PipelineResult.FailedStepMessage` makes it to the user
- [ ] make sure we warn if the cache artifact size is too big
- [ ] potentially increase artifact size

**Comment by hatchan** [comment]
I think having a short message in the `FailedStepMessage` is a good start. Then we should include some more information in the logs, with a link to the devcenter explaining the details
