### ISSUE TITLE
Make default cmd "/bin/sh"

### ISSUE THREAD

**Issue by faiq** [wercker/wercker#118]
Right now the default cmd is set to "/bin/bash" in this line right here: https://github.com/wercker/wercker/blob/master/docker/box.go#L85

since docker is moving official images to alpine it would make sense to make the default /bin/sh
it would also save me a lot of time debugging this mistake over and over again. thoughts?

**Comment by hatchan** [comment]
Most of our steps use /bin/bash. And users might use bashisms in their script steps, which will stop working if we change to `/bin/sh`

**Comment by JeanMertz** [comment]
This has tripped me up before as well (also while using an Alpine image).

**Comment by ooesili** [comment]
What about `/usr/bin/env sh`? Not all distributions put `sh` in `/bin`, but I have yet to seen one that doesn't have `/usr/bin/env`.

**Comment by faiq** [comment]
pretty much a clone of  #70 -- closing
