### ISSUE TITLE
Build/store Step Errror Should Be Shown

### ISSUE THREAD

**Issue by loganwedwards** [wercker/wercker#168]
Props to the Wercker team with helping me here, but I had an issue where my pipeline was failing on the build step due to exceeding the 1000MB quota on the docker image. The UI would just show that the Build/store step would fail on `Storing artifacts`. Exposing the actual error to the user would have saved me quite a bit of head-scratching.

**Comment by Tonnu** [comment]
Not sure when this was implemented exactly, but this error is being shown on the Wercker platform already: 
![screen shot 2016-07-05 at 14 34 38](https://cloud.githubusercontent.com/assets/1899787/16584697/a06f0486-42bd-11e6-809f-a593ccfbaead.png)
