### ISSUE TITLE
wercker creates several folders on the project root

### ISSUE THREAD

**Issue by giovannicandido** [wercker/wercker#181]
Hi,

Wercker generates the folders:

_builds
_cache
_steps
_projects

Every time a build is made

plus a litle more files and folders that are deleted when the build executes

Is very annoying and poluted. It should have a .wrecker folder and subfolders

**Comment by faiq** [comment]
Thanks for filing this issue, but we updated this weeks ago 

https://github.com/wercker/wercker/pull/65

puts everything inside a .wercker directory. please update your version of wercker if you want to use the new changes.

best,
faiq
