### ISSUE TITLE
store step should explain better what it is storing

### ISSUE THREAD

**Issue by flenter** [wercker/wercker#189]
Now there's very little output:
```
Storing artifacts
Storing artifacts complete
```

We should display what we're storing in more detail: 
storing: $WERCKER_SOURCE_DIR or $WERCKER_OUTPUT_DIR
and maybe some generic info regarding nr of files/ size?

Related issue: #168

**Comment by hatchan** [comment]
Also better error handling when something fails, ie. when the size it too big

**Comment by flenter** [comment]
Yep, that's the related issue #168

**Comment by Tonnu** [comment]
Didn't notice you were assigned @flenter, but took the liberty of submitting a PR (#207)
