### ISSUE TITLE
Add support for local deploys

### ISSUE THREAD

**Issue by faiq** [wercker/wercker#20]
_From @Tonnu on January 21, 2016 9:30_

Because of how sentcli behaves in the cloud environment versus locally, local deploys don't work. 
What needs to be done to support this?

See also this issue: https://github.com/wercker/support/issues/137

_Copied from original issue: wercker/sentcli#651_

**Comment by Tonnu** [comment]
This was fixed by https://github.com/wercker/wercker/pull/74 i believe.
