### ISSUE TITLE
internal/docker-push to ECR doesn't work

### ISSUE THREAD

**Issue by mies** [wercker/wercker#219]
Output on Wercker platform is as follows
```
Pushing to registry
Preparing: a78a5489d71b
Preparing: 4fe15f8d0ae6
```

**Comment by faiq** [comment]
I don't think this has to do with ECR, more along the lines of wercker not waiting for the step to complete. The only ECR related bits are finding the right authentication strategy to go with.

**Comment by faiq** [comment]
it does work
