### ISSUE TITLE
Scratch and push should include config in checksum calculation

### ISSUE THREAD

**Issue by faiq** [wercker/wercker#24]
_From @hatchan on October 20, 2015 11:55_

Currently when two scratch and push with the same content, but different config will result in the same ID. This causes docker not to upload the resulting layer, and thus the old layer gets used, with the incorrect config (ie. working dir, entrypoint, cmd, etc)

_Copied from original issue: wercker/sentcli#600_

**Comment by hatchan** [comment]
This was resolved by randomly generating a new ID for each push. This is the same behavior as docker.
