### ISSUE TITLE
Access build files even on failure

### ISSUE THREAD

**Issue by giovannicandido** [wercker/wercker#247]
Use case scenario is simple: 

1. The gradle test fails and writes the results on **build/reports/tests/index.html**
2. To know way user need to open the file
3. But the file is on the container. How to access?

I try to find the file inside **.wercker** directory but not luck in any way, even searching recursive for the failed exception.

The cause is difficult to diagnose without open the stacktrace result. gradle test --stacktrace is no help

**Comment by flenter** [comment]
You probably want to run the build with the `--attach-on-error` option. When the build fails, you'll end up inside the container so you can check files and even execute commands. See also: http://devcenter.wercker.com/cli/configuration/options-and-flags.html#-a-name-attach-on-error-class-anchor-a-attach-on-error

**Comment by giovannicandido** [comment]
@flenter Nice, that solves the issue. I miss that in documentation

**Comment by fabioknoedtbcgdv** [comment]
I don't see these files in the Mac version of `wercker` though. I need to use `wrecker build --attach-on-error` to have access to them.
