### ISSUE TITLE
Some service boxes not being shut down properly

### ISSUE THREAD

**Issue by faiq** [wercker/wercker#27]

**Comment by faiq** [comment]
_From @hatchan on August 26, 2015 18:48_

thought we fixed this with #566

**Comment by faiq** [comment]
_From @mwhooker on August 26, 2015 22:34_

I think I had this patch when I ran in to the issue, but having trouble
reproducing it reliably.

--Matthew Hooker

**Comment by faiq** [comment]
_From @mwhooker on August 27, 2015 22:55_

after seeing this behavior on @mies's laptop, I think services do not get cleaned up when the build fails or if we panic

**Comment by termie** [comment]
not sure how this was re-opened, but closing now
