### ISSUE TITLE
Unable to push to Docker Hub using internal/docker-push step using default registry endpoint configuration.

### ISSUE THREAD

**Issue by rikgibson** [wercker/wercker#347]
When using the internal/docker-push (or internal/docker-scratch-push) step, if the "registry" endpoint property is omitted from the wercker.yml the push now fails, returning a "404" error. If an explicit v2 endpoint is specified - "registry: http://registry.hub.docker.com" - the push works correctly.

**Comment by kokaz** [comment]
Fixed by https://github.com/wercker/wercker/pull/348
