### ISSUE TITLE
go build failed with go1.10

### ISSUE THREAD

**Issue by shihchang** [wercker/wercker#353]
go build passed with go1.9.3.darwin-amd64.pkg
go build with go1.10.darwin-amd64.pkg failed with following error:
# github.com/wercker/wercker/vendor/github.com/google/certificate-transparency/go/x509
vendor/github.com/google/certificate-transparency/go/x509/root_darwin.go:73: cannot use nil as type _Ctype_CFDataRef in assignment

**Comment by lake-of-dreams** [comment]
I fixed that manually by updating few packages (cfssl,proto,certificate-transparency-go). Attached is my vendor.json
[vendor.json.zip](https://github.com/wercker/wercker/files/1785003/vendor.json.zip)
