### ISSUE TITLE
Azure ACR : Docker push is not supported in several locations.

### ISSUE THREAD

**Issue by moaikids** [wercker/wercker#364]
<http://blog.wercker.com/pushing-to-azure-with-wercker>
This blog article says that wercker's `internal/docker-push` step support to push to Azure ACR. 
But when I tried it in my environment (in `japaneast` location) occurred following error.

```
autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'japaneast' and API version '2016-06-27-preview' for type 'registries/GetCredentials'. The supported api-versions are '2016-06-27-preview'. The supported locations are 'westus, eastus, southcentralus, westeurope'.
```

Apparently, it seems that version of the Azure SDK you are using is very old.
`2016-06-27-preview`

Any have plan to upgrade SDK Version of Azure?

**Comment by lake-of-dreams** [comment]
@moaikids We have started to look into this

**Comment by lake-of-dreams** [comment]
@moaikids This should  be fixed now. Please check and let us know for any further issues
