### ISSUE TITLE
Is it now - after opening up the source - possible to have a self-hosted instance of wercker?

### ISSUE THREAD

**Issue by keyvan-m-sadeghi** [wercker/wercker#5]
Hi Wercker team,

I've been following the development of Wercker for some time now and going partially open-source is a great move in the right direction IMHO, thumbs up.

Was wondering if it'd be possible now to have an instance of Wercker set up on one's own server and if so, would there be restrictions on no-of-active-jobs, etc?

**Comment by mwhooker** [comment]
Hi @keyvan-m-sadegh,

Thanks for your interest. It's not possible to do what you're asking quite yet, but it's something we've been thinking of, and is something we want to provide. Open sourcing the wercker cli tool is a step for us in that direction. I don't want to promise anything, as the project isn't set in stone, but it'll probably be a major focus for us in the near future.

Would you mind if we contacted you in the future as we're developing the requirements? It would be helpful to come up with some use-cases.

Feel free to re-open this in the future if you want an update. 

Thanks!

**Comment by keyvan-m-sadeghi** [comment]
@mwhooket thanks, this was buried down a pile of notifications, sorry for the late response. Yes, you could contact me anytime, I'm keyvan.m.sadeghi@gmail.com, any updates after six months?

**Comment by Hashfyre** [comment]
Hi @mwhooker We at Razorpay have been using wercker for over an year now, and we love the product. However in future due to compliance issues, we may have opt for an in-house solution. Would be amazing if wercker starts offering a self-hosted solution in the future. 

You can notify us of any progress at devops@razorpay.com
