### ISSUE TITLE
AWS ECR support

### ISSUE THREAD

**Issue by AndreCapelache** [wercker/wercker#58]
Support to push ECR private repo.

**Comment by sgoings** [comment]
Related #25

**Comment by chiefy** [comment]
:+1: would love this feature.

**Comment by shantanupanda** [comment]
+1

**Comment by Morriz** [comment]
Any ideas when this will hit? It's very hard to use ecr otherwise...

**Comment by MaikuMori** [comment]
This would be nice. ECS has some problems with Docker Hub auth sometimes. Also keeping images closer to AWS infrastructure should help speed things up.

**Comment by jpadilla** [comment]
Anything that we could help with to help this happen?

**Comment by vladgolubev** [comment]
@jpadilla it's shipped just few hours ago.

blog.wercker.com/2016/05/09/Introducing-Wercker-Workflows.html

**Comment by jpadilla** [comment]
@vladgolubev nice, just requested to try it out.

**Comment by Tonnu** [comment]
This is live for Workflows users. Documentation on how to push to ECR can be found here: http://devcenter.wercker.com/docs/containers/pushing-containers.html
