### ISSUE TITLE
I can't run wercker

### ISSUE THREAD

**Issue by mateeyow** [wercker/wercker#69]
Hi, I can't seem to run wercker on my linux. I have already installed brew and even tried the curl installation but this error message always appears: `zsh: exec format error: wercker`

**Comment by hatchan** [comment]
When using Linux, you need to follow the Linux instructions: http://wercker.com/cli/install/linux/

**Comment by mateeyow** [comment]
Oooh. There was an option? Didn't saw that one. Thanks!
