### ISSUE TITLE
unable to build successfully a yeoman web-app project from GitHub 

### ISSUE THREAD

**Issue by anbestephen** [wercker/wercker#76]
I can't build a yeoman webapp project in Wercker. I suppose i have used the recommended Wercker setting but still am getting this error message:

```
export WERCKER_STEP_ROOT="/pipeline/npm-test-80822b9b-5805-45f9-8803-8eb51fa740f2"
export WERCKER_STEP_ID="npm-test-80822b9b-5805-45f9-8803-8eb51fa740f2"
export WERCKER_STEP_OWNER="wercker"
export WERCKER_STEP_NAME="npm-test"
export WERCKER_REPORT_NUMBERS_FILE="/report/npm-test-80822b9b-5805-45f9-8803-8eb51fa740f2/numbers.ini"
export WERCKER_REPORT_MESSAGE_FILE="/report/npm-test-80822b9b-5805-45f9-8803-8eb51fa740f2/message.txt"
export WERCKER_REPORT_ARTIFACTS_DIR="/report/npm-test-80822b9b-5805-45f9-8803-8eb51fa740f2/artifacts"
source "/pipeline/npm-test-80822b9b-5805-45f9-8803-8eb51fa740f2/run.sh" < /dev/null
npm info it worked if it ends with ok
npm info using npm@3.6.0
npm info using node@v5.6.0
npm info lifecycle baltimoresite@~pretest: baltimoresite@
npm info lifecycle baltimoresite@~test: baltimoresite@

> baltimoresite@ test /pipeline/source
> grunt test

sh: 1: grunt: not found
npm info lifecycle baltimoresite@~test: Failed to exec test script
npm ERR! Test failed.  See above for more details

```

**Note:** Here is the [link](https://github.com/anbestephen/wercker-test) the repo, and you can find the werker build failure message [here](https://app.wercker.com/#buildstep/56c097ffa21e380e1e034f12)

**Comment by mwhooker** [comment]
My guess is that the node box doesn't have grunt installed. I'm not sure if the node box is Debian based, but you could try apt-getting grunt if it is. Otherwise you may have to download it

—Matthew Hooker

**Comment by hatchan** [comment]
This docker container that you are using, contains the `NODE_ENV=production` env variable. This causes `npm-install` to only install regular `dependencies`, and not `devDependencies`. 

You need to set the `NODE_ENV` environment variable to `development`:

```
- script:
    name: set NODE_ENV
    code: export NODE_ENV=development
```

**Comment by hatchan** [comment]
I just checked, and I might be mistaken. It was another node container that set the NODE_ENV

**Comment by anbestephen** [comment]
@mwhooker, @hatchan it would be appreciated if you could suggest any solution, thanks

**Comment by hatchan** [comment]
@anbestephen You did not install the `grunt-cli`, most of the time this is installed globally, but I send you a pull request where it is included in the `package.json`.

**Comment by anbestephen** [comment]
It works!! thanks @hatchan , though the [build](https://app.wercker.com/#buildstep/56c328f7b33fd8bc4e106473) failed with this message:

`Warning: PhantomJS timed out, possibly due to a missing Mocha run() call. Use --force to continue.`

which seems an issue related to test framework , the **grunt** issue is fixed now
