### ISSUE TITLE
Allow services to publish ports

### ISSUE THREAD

**Issue by mbrevda** [wercker/wercker#78]
During dev/build, it can sometimes be necessary to connect to a service via it's published ports. Allow for these ports to be exposed.

It might also be useful to allow port publication to be specified by wercker.yml for the box as well as services.

/via https://werckerpublic.slack.com/archives/wercker/p1455618009000023

**Comment by hatchan** [comment]
This definitely can be handy. During development it might be necessary to inspect/edit the database while developing using some UI tool. 

Currently we only link the service boxes to the main box, we should investigate if publishing these ports will give any conflicts.

**Comment by mbrevda** [comment]
Any way to expedite this?

**Comment by andre-hh** [comment]
+1
Is there a workaround for this?

**Comment by hatchan** [comment]
Implemented in https://github.com/wercker/wercker/pull/161
