### ISSUE TITLE
auto update homebrew-wercker on deploy

### ISSUE THREAD

**Issue by mbrevda** [wercker/wercker#81]
Remembering to update homebrew-wercker after every deploy can be a pain. If this can be automated during deploy, that would make it a lot simpler.

**Comment by Tonnu** [comment]
Thanks for the suggestion @mbrevda, we've already started on automating this I believe so shouldn't take too long

**Comment by mbrevda** [comment]
I guess long is relative 😉

**Comment by Tonnu** [comment]
This was resolved by #197
