### ISSUE TITLE
Environment variables can't contain $ char

### ISSUE THREAD

**Issue by davegri** [wercker/wercker#82]
Environment variables with $ char cut off everything after and including the $.

Steps to reproduce:
1. Create environment variable TEST_VAR - "abc$efg"
2. Print variable during deploy - 'abc'

**Comment by hatchan** [comment]
This is expected, as everything after the dollar sign will be interperted as another env var, in this case the env var `$efg`. However it should be possible to escape a dollar sign, which I do not think it is possible at this time. By doing something like `abc\$efg`

**Comment by faiq** [comment]
same as #158 closing
