### ISSUE TITLE
docker-scratch-push fails on docker 1.10

### ISSUE THREAD

**Issue by termie** [wercker/wercker#92]
they've changed how image IDs work so we need to create ours in the same way

**Comment by cescoferraro** [comment]
@termie can you show us a workaround for this?

**Comment by faiq** [comment]
It looks like imageID's are now content addressable in docker 1.10 and beyond see here for more details: 
https://github.com/docker/docker/wiki/Engine-v1.10.0-content-addressability-migration

**Comment by hatchan** [comment]
Resolved in #137
