### ISSUE TITLE
Support reading command line options from the env.

### ISSUE THREAD

**Issue by hvdklauw** [wercker/wercker#98]
I think it would be really nice if the CLI would support getting some (all?) of it's options from the envrionement and it seems the cli library that is used [supports it](https://github.com/codegangsta/cli#values-from-the-environment).

Good example would be to change the build working-dir without having to specify it all the time.

**Comment by mwhooker** [comment]
Hi @hvdklauw good idea. I added the working-dir flag as an envvar in pr #100.

Are there any other specific options you'd like to see? Quite a few of them are already configurable using environment variables. See https://github.com/wercker/wercker/blob/master/cmd/flags.go for the complete list.

If there are any others you'd like to see, let me know and I'll update the PR.

Thanks

**Comment by hvdklauw** [comment]
Hey, thanks !

Looking at the list I would say environment for the dev command is another good candidate !
As well as wercker-yml.
especially in a python virtualenv where you can set these variables upon activation and then have them applied as long as you are within the virtualenv.

**Comment by mwhooker** [comment]
done! we'll get this reviewed internally and merged
